### PR TITLE
feat: add disable preload option & crossorigin

### PR DESCRIPTION
**Pull request by Geminii**
In order to preserve your work @arkhamvm, i created this PR to merge your work into this extracted Yandex Metrika module. 
Like purposed by @pi0, we want to keep your work 😀😀

Next step will be to reorganize the project by applying your recommendations

### CODE REVIEW

**Comment by arkhamvm** [comment]
Cool, thanks. The feat is to disable preload in some cases like amp. Cross-origin needed to pass user cookies because it is an analytics tool.

**Comment by pi0** [comment]
Thanks @Geminii for PR and of course @arkhamvm for creating it <3 Regarding cross-origin, is there any docs for yandex metrika that recommends it? Cookies are needed to keep session id (but for domain itself). Sending them to a remote origin can concern both security and privacy.

**Comment by Geminii** [comment]
It could great to precise this option into the README about usage 😀

**Comment by arkhamvm** [comment]
@pi0 amp pages stores in google/bing domains, so I think the script will send an ajax request with all credentials anyway.
@Geminii should I add it?

**Comment by pi0** [comment]
Hi @arkhamvm Regardless of google amp, we should **not** send credentials unless there is a clear documentation that we need to set this attr for some reason.

**Comment by arkhamvm** [comment]
@pi0 well, without cross-origin this script will be loaded by the browser a second time with cross-origin, preload just have no sense in that case.

**Pull request closed without merging**
